version: "3"

services:
  api:
    container_name: api
    env_file:
      - ./backend/src/.env
    build: 
      context: ./backend/.
      target: production
    ports:
      - "3080:3080"
    depends_on:
      - db
  
  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  app:
    container_name: app
    build:
      context: ./frontend/.
      target: production
    ports:
      - "3000:3000"
    depends_on:
      - api
  
volumes:
  mongodb: