version: "3"

services:
  api:
    container_name: api
    env_file:
      - ./src/.env
    build: 
      context: .
      target: production
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
  
  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
  
volumes:
  mongodb: